import type { Metadata } from "next";
import {  Rubik, Rubik_Mono_One, Bricolage_Grotesque  } from "next/font/google";
import "./globals.css";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});

const rubikMonoOne = Rubik_Mono_One({
  weight: "400", // Only available weight for Rubik Mono One
  variable: "--font-rubik-mono-one",
  subsets: ["latin"],
});

const bricolage = Bricolage_Grotesque({
  variable: "--font-bricolage",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${rubikMonoOne.variable} ${bricolage.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
